### ISSUE TITLE
Smart Table Props Color

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#156]
Hi,

I tried to change colors of cells when clicking sort. I used  HandleSortValueChanged event but I cannot make use of the _styles.
Is this possible changing colors of the cells(odd) when sorted in smart table?

![image](https://user-images.githubusercontent.com/21064877/205126880-bddaa67b-6241-4147-b06d-fbc829296f67.png)

Thank you

**Comment by xidedix** [comment]
@32x0lf what you're looking for is to overwrite css variables for `.table-striped`
For example, in `src/scss/_custom.scss` file:

```css
// Here you can add other styles
.table-striped {
  --cui-table-striped-bg: lightpink;
  --cui-table-striped-color: darkred;
}
```
